name: SAST - Snyk

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Instalamos la herramienta CLI de Snyk oficialmente
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      # 2. Ejecutamos el comando manualmente.
      # Esto asegura que el archivo snyk.sarif se cree en la carpeta correcta.
      - name: Run Snyk Code Analysis
        run: snyk code test --sarif-file-output=snyk.sarif
        continue-on-error: true # Snyk devuelve error si halla fallos, esto permite continuar para subir el reporte
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 3. Verificamos que el archivo exista (Opcional, para depuración)
      - name: Verify SARIF file exists
        run: ls -la snyk.sarif

      # 4. Subimos el reporte (Actualizado a v4 para quitar el warning)
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Se ejecuta aunque Snyk haya encontrado vulnerabilidades
        with:
          sarif_file: snyk.sarif
          category: snyk-sast
