name: SAST - Snyk

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk Code Analysis
        run: snyk code test --sarif-file-output=snyk.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Verify SARIF file exists
        run: ls -la snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Se ejecuta aunque Snyk haya encontrado vulnerabilidades
        with:
          sarif_file: snyk.sarif
          category: snyk-sast
